version: '3.8'

services:
  # PostgreSQL 数据库
  db-postgres:
    image: postgres:17-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      TZ: Asia/Shanghai
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - appnetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/libs/init/db-postgresql17.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
   

networks:
  appnetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local